services:
  - type: web
    name: vidquery-api
    env: python
    repo: https://github.com/Anwar-Qureshi/VidQuery-RAG
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
